sudo: false
language: node_js
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
node_js:
  - "12.16.1"
branches:
  only:
    - develop
    - master
    - /hotfix\/.*/
    - /^greenkeeper-.*$/
    - /^greenkeeper/.*$/
install: npm install
