apiVersion: v1
kind: Service
metadata:
  name: jass-challenge
  namespace: default
  labels:
    app: jass-challenge
spec:
  type: LoadBalancer
  selector:
    app: jass-challenge
  ports:
    - port: 8080
      targetPort: 3000